sudo: true
language: node_js
node_js:
- 14.16.0
cache:
  yarn: true
before_install:
- chmod +x ./.travis/*.sh
- "./.travis/validate_last_commit_message.sh"
- npm run tools
- yarn config set ignore-engines true
install:
- yarn
script:
- echo "Running tests against $(node -v) ..."
- yarn validate
jobs:
  include:
  - stage: release
    node_js: 14.16.0
    script:
    - echo "Deploying to npm ..."
    - "./.travis/publish.sh"
branches:
  only:
  - master
env:
  global:
  - secure: or3KhMRZUHUN65YJ8vaIwN4hVKv5eoaHnZL77jzMfNlvLRCKFT9xjyU0eLKLKjdYJg4F2GEcGrqZyeEWBh3FUS9jMNU3x4Tf3Q5r6M3iTMDr3RkFzJV/QnKDRPUt3bKcA2SojRERKZtRg4o2qBRG9aqwV5ooR3XR0HW/+R8dEsusud4fZjJvk34bGQw+C+9MrqKMJda071PMhYUPy8auJMDP33j4ulo7NUTcOD8DH8r3PHP72Pv7EjiPGTvOHtQrKRequePwKimEI7H2nLsnV2GZb0sr9mGFCsBnAoZ3laEDvG6aEO8is0H66fCXwZxkaNZSY7DuOVFKTUsaAtT1jQH+Xc3AxLoeEStaXEW6ddz7PMSSpJhFtlRMkseOR9VzgAr27oAB5mCAnaTTIfuIBd/chqLPjQOXkc5/g9emuTnevDSEmwz7ABl4tsnQg3T/cHS8GnJD4BttNB1nC2NISsM9TWdtvBNKjL5Y8NX+HmvIryrkRnXixtyOoU9Pz3vWaeIvzfDN1jTUADfV+Gt815DBO54FxhDSxXNM/VcSNPfgpDN8mAdVNNuzxMMKtj/oC2sJo2535lAu30FuBmdlT/avZy1blu7InztQOcq6MTTVdXJEY8wyrzWUO9Qe3fKmOudx4KTIYLX9BoU2mFHIypznDjLoGXBMuOe/DbtiXcY=
  - secure: egaVN6KRYWbCUH5uiy7HIjn2nR0NfObQaaqcAhcdkKbu/wM98Mwm3DNmk8u83hT3sLHNiUXa9luEVDcHeHNfweRpFK9AaziL0BveNHISS4NQfv7kuOyjFHIyBRS6XoCOg+A9ZivI1IyORDUycL9xqFOGuLWR0UJ0Jp1H1Ecn0XGiwfI2aLr4AyM24J7AvkAAhnX4TfB2leJ+Jnk4PNKsAvbT0iAKM7l/rNlyA4sDsf1k5XsVXF/P+CxV5hzOQol7ERWjk39YQAWO6MlHU2sMeRFuz9G0xPn7Oyb93WAKow3TN3SqMz+aN1TxW3Qnfh7PYKS9XCPXLf9cdvRgdF9Vg3AZ4BmxU2+iqJRasFCX/imR1cU2gT+EC6y7D4QsAZSqT2mqPRyoEUOrAQoSlhN9EYDflSOc6Qv+DHSCONCHeAZmz49T6j8nRtUNp2OLSxGZwhT+8Fzg0RMbob49nWOdK2Et9sS8EvW8xV43HOM0jyBuoQBRlw/r/M4Rf6fTDXMU4+/3RAQA20yHziteVVLO59QsiiolIKG98dASaU+qYg/A5aS05RlReLap3KXSNQa1ggOSPXbTxyAVUQSf/kE54JLd+vOi9smT9MoLZNW72I6TqesmSrxHtbEs8JMNwclZZt7H7wz6x5RvlC+PObGxBF9r27C9l/dZ2fPhn1vdG4Y=
