sudo: true
language: node_js
node_js:
  - 9.11.2
  - 8.15.1
cache:
  yarn: true
before_install:
  - chmod +x ./.travis/*.sh
  - './.travis/validate_last_commit_message.sh'
  - npm run tools
  - yarn config set ignore-engines true
install:
  - yarn
script:
  - echo "Running tests against $(node -v) ..."
  - yarn validate
jobs:
  include:
    - stage: release
      node_js: 8.15.1
      script:
        - echo "Deploying to npm ..."
        - './.travis/publish.sh'
branches:
  only:
    - master
env:
  global:
    - secure: mYnl8de/7TiFCslALcUN9MYFnolMTu8K2yLarepsRAM8Azcchlx/9jqcybq+aY8YqspGw8Lhz4/BB1AvbwsQWbck100o0H4iA1MbLKAbL+dYnn0t5wmvcLbpLyLNN/G2Pb+8hv6Yo/nUddatTeMwlLkmh/5zHhZUM3O2HG28jtny2n0L97WUfxUtVu8gPSdpn1PvCF0gKhOTiAG4OcCmH/eZSJqD5v1W+EUQI3e3PfDQOASyLCiftl6KJQ1oIp35NFtOjndMZJ9xVbDRbFBi6u6XoVEod/DNFo9LNJXlhVui47sPzffc/YQ1OCDaVWuBWGJ6CZnhfYDZD7/n9GEbWugXvlg4/+Ul6ITwsXFXN0Q/L5kdsPQr7uU9UcKZ9Ene23dTV+MrnUGINWiuQs9VgkRa5IbyMfEIGvFAuMDhSXNEBTIw0pBziV/Svzpcow4ekb9H8k3YBLWp6gFJZxFuxxfhBSh79si+fRdgfUP9e0lzb6bwNMwSE+JP5QqJxhE1STBHAzjkW9HbysL4hSA0mDSWafSJkPYvpUzo1QSVUwUsiE57zzyhyleUIOa8BrYbTW3GVS01He48tk7DFlihI7ghIyeyUfb/22uqxrICFxqw/xz5YZTxc3UF8Ex8jv0a+YxREw33tWi+Qw5qFl/vJbhKGdUVewZy3NWDWO68T6s=
    - secure: Jtch7YL0wzvUp0MS+2VvwGTCOlazCV5uTPCMO7MXTfWAxkIMjMJwNSy/1pgvRVzpKribciZsHLBdykxjEDxZnZTqWSEuprOWrvN/sRXbNIMYXkKAmqczkD1RQJQvSk1phsObqIY+35SIVUiEsXPOJAdPUjEYgd2nSk+out475Upu1qTLRH7+7QpCCbLzR1LbTSmnTJfXIkGGLPHzzIb825BPXjfgTAJMkI0IeFOT4xc9bMOJZ1b4Rgkg+bbXMza1988ptIu8A/t+nFY/LOeEb1IpjViWEmEdtXh3jiKytEuibl4+FJ0+r9pobtv/0aGP26tw+FbKfjY0CeGPU2qUeblFKSUutbo17yAaSXZa8zvACG/lPynfoSTJpCu3s0r3XytnheNcH9WfqRwxXImP+r8aJtrCzlk75Th8egCFVb4l18ppbZYKBDx1DsE3mxe/P4lU0Rh33TjOZ+hhikbHFfEehXYcuFX8p+3zIqGwZ4nTbbQDoLPr5gB/7D49r8FGfk01r40HZAKpt9heRt12MCRhyBVdj0+A2OGIxQ2KmpY78KBIVO0NAcKnelXTATgAjMBNOW4tVvMGJUFzcBDAFVR5GHFbGUJStX05GOpXpYGSJAZzeuZLRHaIhZI5U7vzkcxU2M5lryoJnEI8v+CkwyHhQ4nOjcxSJm3O00hFjDI=
