sudo: true
language: node_js
node_js:
  - 9.11.2
  - 8.15.1
cache:
  yarn: true
before_install:
  - chmod +x ./.travis/*.sh
  - './.travis/validate_last_commit_message.sh'
  - npm run tools
  - yarn config set ignore-engines true
install:
  - yarn
script:
  - echo "Running tests against $(node -v) ..."
  - yarn validate
jobs:
  include:
    - stage: release
      node_js: 8.15.1
      script:
        - echo "Deploying to npm ..."
        - './.travis/publish.sh'
branches:
  only:
    - master
env:
  global:
    - secure: jhv7JIRCcLLYVRQ/mbp5XrlMGnZTh5rxhK334YjEKvdsgqMNhhl1hn+SZQfb+Tisja9+xNzseZjaLtJ9SIkB0yKaju8Zdhc3z6klV5hi5SuXgvt2+/9KnzbOuUR5weCrDhuYIlYa7d89+KCSd+xp53mGPID3FW4lG99HjGEkQzPGID/sqqeyFFZx793gHEBPqETlheKyOLxd8zVeKPPG9eIe5ZTX3ilUKFZ+W+0oOBa9kT2U5tK1NkrEb+5+DLn9FXw1+RAf5dhGpHa8lh470XDwXZr/jfH9kX6djq2EKQIv7HxpMY9A5Py71zAah3uek1o8JikKAsh3qcDtdozxpVd5bDNhj/wkVDSei29cWNJ35lE7x40tI/BpwTGWzMT/rvF5e+Fd3DO5yMlr9xg5EN/RBBcXdzja2AHhBf3QLUI4P6+TkpWCqs3NHzxxrIK/bDLBihGKnJh9alD4YoXQcfnFfM8MTFzPLUNpdJcsznk0G3LuhLHFMlVmSb7eYJUtnOCJNsJ8t73IMMEjnOVp9Xfl9cqUmuJI066pyOS9y4uo4c/kJwONzQGExfmqq7ycN2fldFRH/HD4W2xZw8lDLn/Hs4frusQxdqg06nrotda6+94sOPCyjzh9TJcLxl1adYYPW5FX3bwyv0yY7Eibj7gqyrq8fjJsiw/AcIgyoBk=
    - secure: Uh151mcW15fxWQVXWS1Dg7NQ8tiwoQCMyRj0a5naD0XwYrO2f53mK/xr7aoWU1AWsPCRef/fnv8ffHbb63LLacJKioaat34+ATc5AZmcRKh+NcDC3zfN4o554dKRYW0+m/17EJdo8vRawKdZcrVFFd6l9sxXYRSQLxb2Oq+o/rpD0rslmdkubhzgcuvz9MrFXkwQhBROP6lasoiYI23Bb3ECoC8lZbW/fjIvNQgYfyI3o8xkKCY57oTpeioEs7WP9J60Ahy8/C5lTnTkjQXCzxGZMwcjbW4J+WVBhx+XpWdeOpOi79SHccOsU1PGl+vaZsCZTd93ntiiN2E6LK55eYpNhdsohwK9cYHn9rA2Vqd93+fxXjq22Nwg6KlXpuUMaW/r8t3M3W0fYXdbMfc/FJAXPN13LaMxjinCke3DbQiSvJp8JemIJTjQScVGkFN9Q1AYlw3oyoZOgu1d/FOEvzJrOBFvF9EPFOq6TlC/a4EgE5peRQYs2hFvzeo4vfRoH45KXODddFk1wHyWJGl22+6Yr4y/4ppplMXdLo07wWJc85OqVzHOWmwDzPz8969oFb05v+r/V9tQ/7kYVfZmNXx/kg7ebuM5/uEfKQYsIpkyKj8OP9ovtOxc6/Q7KWGicwutaUafNPIJx6+vnTuLTWHE5VPAxqCXBVRA/i2VKcw=
